version: '3.4'
services:
  db:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    ports:
      - '5432:5432'
    volumes: 
      - ./data:/var/lib/postgresql/data
      - ./data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080


  front:
    container_name: saegus-front
    restart: always
    depends_on:
      - back
    build: ./front
    ports:
      - 3000:3000
    volumes:
      - ./front/src:/app/src
    environment:
      - REACT_APP_API_URL=${BACK_DOMAIN}:${BACK_PORT}

